### ISSUE TITLE
clusters are cut off on enter

### ISSUE THREAD

**Issue by russellsamora** [sxywu/hamilton#13]
<img width="887" alt="screen shot 2016-12-05 at 9 58 35 am" src="https://cloud.githubusercontent.com/assets/324631/20889571/75d0d65a-bad1-11e6-939e-13c9670c1289.png">

**Comment by sxywu** [comment]
@russellgoldenberg can you expand upon this?  do you mean the dots at the top?  or?

**Comment by russellsamora** [comment]
yeah it looks like incomplete clusters of circles at the top and bottom. Those were cut off by the browser window (not just my screenshot)

**Comment by sxywu** [comment]
talked to @russellgoldenberg, the dots are visible on scroll so closing issue as won't fix.
